# @package _global_
# SPDX-License-Identifier: LicenseRef-SAM
# EfficientSAM3 (EfficientViT-B1 + MobileCLIP-S0 ctx16), base SAM 3 lineage (image).
# Image base with the vision trunk swapped to EfficientViT-B1.
defaults:
  - efficientsam3_image_base
  - _self_

model:
  vision_encoder:
    vision_backbone:
      trunk:
        backbone_type: efficientvit
        model_name: "b1"
